<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-23 21:40
=======
# Generated by Django 4.1.13 on 2024-12-14 14:58
>>>>>>> dev-branch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
