<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-24 14:54
=======
# Generated by Django 4.1.13 on 2024-12-17 16:16
>>>>>>> dev-branch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattachment',
            name='name',
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=120, null=True),
=======
            field=models.CharField(blank=True, max_length=255, null=True),
>>>>>>> dev-branch
        ),
    ]
